### ISSUE TITLE
Expand MailResults Support

### ISSUE THREAD

**Issue by rlaurb** [SwiftUI-Plus/MailView#1]
## Describe the feature
I would like to see a simple `standard` completion handler for .mailCompose(). The handler would use the MFMailComposeResult to display a simple alert. Since the completion handler is optional, adding it to the repository would not impact any existing users.

## Is your feature request related to a problem? 
No problem. This is an added feature with no impact on existing code.

## Proposed solution
The proposed solution (attached) has two parts — a static function that returns a text string for each possible MFMailComposeResult value and a view modifier that displays an alert that uses this text string.

## Alternatives considered
The current implementation has provision for a completion handler but includes none. So current practice is to require users to create their own if they so wish. 

## Additional context
none

[MailResult.swift.txt](https://github.com/SwiftUI-Plus/MailView/files/14858718/MailResult.swift.txt)

**Comment by shaps80** [comment]
In all honestly, I had completely forgotten about this repo haha. It was some time ago and hasn't had a lot of activity.

First up, let me just say thank you for discovering and using this library. I deeply appreciate input and suggestions and contributions.

That being said, I actually think the approach in this version doesn't align well with similar API available in standard SwiftUI.

In addition, I'm not sure I agree with the solution provided, in particular using a String vs a full type isn't ideal or practically useful for most uses.

That all said, I'll take a deeper look today and perhaps post a whole new approach that better aligns with modern SwiftUI.

I'll post an update later today so you stay in the loop..

**Comment by shaps80** [comment]
@rlaurb as mentioned above I've revisited this library and just realised v2.0 which is a whole new approach that's far more usable in more places.

I've deprecated the existing API but overall its simpler to migrate since you mostly just delete existing code and replace it with a single line.

The modern convention in SwiftUI for this kind of feature is to provide a custom button, similar to `PasteButton` and `ShareLink` for example.

__TLDR;__

You can refer to the README for details, and ofc use the latest version. However I'll drop a Demo project here for your reference.

__Details__

I originally wrote this package as a part of a custom "share sheet" that was required for a client app. I've since refactored into different versions, so 2.0 represents the learnings from the past 3 years.

Besides the simpler interface, I've also introduced several key features worthy of mention:

- macOS support
- Automatic alert on error (essentially as per your request)
- Override result handling with a simple modifier
  - `.onMailResult { result in }`
- Concurrency support for Attachments
  - Almost zero memory consumption even for very large files since data is memory mapped
  - Faster loading of the mail sheet, since attachment data is loaded concurrently 
- Attachments are cached as URLs and stored as security scoped bookmarks
  - URL bookmarks are now stored instead, so if you encode/decode mail (say for an drafts feature) attachments should still work fine and be accessible even if the original files are renamed, moved, etc...
  - This also reduces memory footprint significantly since data is no longer stored in the struct
- Added support for parsing `mailto` links, makes defining constants a breeze
  - `static let foo: Mail = "mailto:subscribe@newsletter.com?subject=Subscribe"`
- All types are now Sendable and Hashable
  - Removes warnings in modern concurrency projects and ensures better safety overall.

The previous approach seemed viable at the time, but the biggest issue I personally had with it, was that modifiers can only be applied in specific places. A button by contrast, can _easily_ be used in more places, like `Menu` and `.toolbar` for example.

Also since the internal implementation is just a `Button`, styles and other modifiers 'just work' so you can easily customise the appearance.

That said, there's also a bunch of common APIs provided to simply those use-cases:

```swift
MailButton("Send mail", systemImage: "envelope.circle", item: mail)
    .labelStyle(.iconOnly)
    // by providing a custom handler, the default alert behaviour will be disabled
    .onMailResult { result in
        switch result { ... }
    }
```

Hope you like the additions as one of my only users haha.

[MailDemo.zip](https://github.com/SwiftUI-Plus/MailView/files/14952141/MailDemo.zip)

<img width="448" alt="Screenshot 2024-04-11 at 23 59 22" src="https://github.com/SwiftUI-Plus/MailView/assets/251310/5c44013a-f780-4e1c-93e4-5dbbb92cc94c">

**Comment by rlaurb** [comment]
Thank you! Version 2.0 of MainView is lovely. Much simpler, more elegant and it works great. 

 I’ve incorporated into my new (about to be released) app, Stinkbug. Updating the five locations in the app where it can send email took only a few minutes.

Cheers,

Rick Aurbach

“The purpose of bureaucracy is to compensate for incompetence and lack of discipline.”
– Jim Collins, author & lecturer (1958–)

**Comment by shaps80** [comment]
@rlaurb Amazing! Glad to hear it :) Let me know once its released, would love to check it out.

Btw, any reason you’re not using ShareLink (or my backport of that) so users can choose how they want to share their content?

Perhaps you need to force email? This library isn’t used much I think largely because users would expect a Share Sheet instead. Just curious.

FYI if you haven’t found my backports and other great SwiftUI implementations you can find them here:

https://github.com/shaps80/SwiftBackports
https://github.com/shaps80/SwiftUIBackports
https://github.com/shaps80/SwiftUIPlus

**Comment by rlaurb** [comment]
I have one other thought that occurred to me yesterday (while thinking about applying MailView in a new project that is in early design stage at the moment) —

You define the Address and Attachment structs and the Message enum as public. I find this a bit concerning because I can see many situations where I’d like to use these names for major components of an app. But it seems to me that using them in MailView (which is more of a peripheral part of my apps) introduces a namespace (i.e. name collision) problem. In v1, these terms were sub-structs of Mail, which prevented name collisions from occurring.

Am I missing something here? Or do you think this is a serious concern?

Cheers,

Rick Aurbach

“The more physics you have the less engineering you need.”
— Ernest Rutherford, physicist, Nobel laureate in chemistry (1871-1937)

**Comment by shaps80** [comment]
No, so ultimately I'd like to rename the whole package to `Mail` actually (future release).

## Module namespace

But for now you just namespace as before, except you use the Module instead.

`MailView.Attachment` etc

This is best practice and preferred generally because in any file you **do not** have conflicts, you can simply omit the namespace.

And since these types are designed to be used and defined in isolation, not to mention abstraction practices in engineering, you'll likely rarely encounter this issue in practical use.

> However, if you do, just namespace in those situations.

## API Discovery

An added benefit of avoiding arbitrary namespaces, is that consumer API is generally more discoverable.

## Background

I have spent a lot of time developing many libraries over the years and my approach has naturally evolved. Before Swift this was a much larger issue, so I guess my previous approach (3 years ago) was just a hang over from those days ¯\_(ツ)_/¯

One thing you can do on your end if you _prefer_ is introduce a simple typealias yourself.

In projects where I know I'll have this issue more often, I'll do something like this:

```swift
typealias Mail = MailView

// now you can reference my types the same way as before without conflict
Mail.Attachment()
```

Now this gives the API consumer back all the power, rather than enforce an arbitrary requirement 👍

Hope that clears things up and thanks for raising 👋

**Comment by shaps80** [comment]
One note on name spacing, I'm certainly not averse to it in the right situations (I don't feel its appropriate here).

`TipKit` for example has a lovely use case for namespaces to simplify the consumer usage.

For example if you look at the implementation you'll note that almost all concrete types are actually defined inside of `Tips`.

This works really well for them because you typically create your own types that conform to `Tip`. So anything that's inside that type will naturally be namespaces and so there's no requirement to write `TipKit.Foo` etc...

This is a really clever approach I've used in other libraries recently to make liberal use of namespaces to either 'hide' detail API that still needs to be public and isn't core to the user experience, or to prevent users from having to type the namespace all over their codebases.

Namespace is kinda like naming things, it's hard and it requires careful consideration. I'm generally very deliberate in all of my choices, especially when it comes to my open source projects. That said, will sometimes get it wrong 😆

But at least I have an explanation right? Haha – Thanks again.
